/**
 * 语言包
 */
let lang = {
  up:                 "悠聘",
  none:               "无",
  search:             "搜索",
  noNull:             "内容不能为空",
  screen:             "筛选",
  city:               "城市",
  salary:             "薪资",
  salaryRange:        "薪资范围",
  jobType:            "工种",
  whatReward:         "什么是入职补贴",
  reward:             "补贴详情",
  treatment:          "薪资待遇",
  jobDescription:     "工作说明",
  welfare:            "福利待遇",
  admissionCondition: "录用条件",
  monthlySalary:      "月薪",
  perDiem:            "日薪",
  weeklyPay:          "周薪",
  hourlyWage:         "时薪",
  payrollDay:         "发薪日",
  salaryType:         "薪资类型",
  basicSalary:        "基本薪资",
  fullAttendance:     "全勤奖励",
  overtimeReward:     "加班薪资",
  jobContent:         "工作内容",
  jobTime:            "工作时间",
  jobTimes:           "工作班次",
  jobExplain:         "工作说明",
  basicWelfare:       "基本福利",
  entryDuration:      "入职时长",
  returnCash:         "赏金返现",
  sexCondition:       "性别要求",
  ageCondition:       "年龄要求",
  educationCondition: "学历要求",
  workExperience:     "工作经验",
};

module.exports = lang;